name: countdown
description: "A tool to convert a date with timezone to a countdown timer."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
